name: Build & Analyze

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build and analyze
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
        with:
            fetch-depth: 0

      - name: Build, Test, and Analyze
        shell: powershell
        run: |
          dotnet sonarscanner begin /k:"Reddit" /d:sonar.host.url="${{ secrets.SONAR_HOST_URL }}" /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
          dotnet build --no-restore
          dotnet test --no-build --versobity normal
          dotnet sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"